'use client';
import { useState, useEffect, useRef } from 'react';
export default function Home(){
 const [messages,setMessages]=useState([]),[input,setInput]=useState(''),[loading,setLoading]=useState(false); const end=useRef(null);
 useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages,loading]);
 const newChat=()=>{setMessages([]);setInput('')};
 async function sendMessage(){const text=input.trim();if(!text||loading)return;const updated=[...messages,{role:'user',content:text}];setMessages(updated);setInput('');setLoading(true);try{const r=await fetch((process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000')+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:updated})});if(!r.ok)throw Error();const d=await r.json();setMessages([...updated,{role:'assistant',content:d.response}]);}catch(e){setMessages([...updated,{role:'assistant',content:"Sorry, I couldn't connect to the AI server. Check that the backend is running."}]);}finally{setLoading(false)}}
 function key(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}}
 return <div className="chat-container"><aside className="sidebar"><div className="logo"><div className="logo-icon">AI</div><span>MyAI</span></div><button className="new-chat" onClick={newChat}>＋ New chat</button><div className="sidebar-section"><div className="section-title">Chats</div>{messages.length>0&&<div className="chat-history-item">{messages[0].content.slice(0,30)}{messages[0].content.length>30?'...':''}</div>}</div><div className="sidebar-bottom"><div className="sidebar-item">⚙ Settings</div><div className="sidebar-item">? Help</div></div></aside><main className="main"><header className="header"><div className="model-name">MyAI <span className="model-badge">AI</span></div></header><div className="messages">{messages.length===0?<div className="welcome"><div className="welcome-icon">✦</div><h1>How can I help you?</h1><p>Ask me anything.</p><div className="suggestions">{['Explain Kubernetes in simple terms','Write a Python program for beginners','Explain AWS architecture','Give me 10 DevOps interview questions'].map((s,i)=><button key={i} onClick={()=>setInput(s)}>{s}</button>)}</div></div>:<div className="conversation">{messages.map((m,i)=><div className={'message '+(m.role==='user'?'user-message':'assistant-message')} key={i}><div className="avatar">{m.role==='user'?'U':'✦'}</div><div className="message-content"><div className="message-role">{m.role==='user'?'You':'MyAI'}</div><div className="message-text">{m.content}</div></div></div>)}{loading&&<div className="message assistant-message"><div className="avatar">✦</div><div className="message-content"><div className="message-role">MyAI</div><div className="typing"><span/><span/><span/></div></div></div>}<div ref={end}/></div>}</div><div className="input-area"><div className="input-box"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={key} placeholder="Message MyAI..." rows="1" disabled={loading}/><button className="send-button" onClick={sendMessage} disabled={!input.trim()||loading}>↑</button></div><div className="disclaimer">MyAI can make mistakes. Check important information.</div></div></main></div>
}
