#!/usr/bin/env python3
"""Render the deployment files from showcase/config/labs.json.

    python3 showcase/deploy/render.py

Writes showcase/deploy/generated/{docker-compose.yml,Caddyfile,requirements.txt} and creates
the host files under showcase/deploy/data/ that hold each lab's persisted SQLite data.
labs.json stays the only file you edit; everything here is derived from it.
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
LABS_FILE = REPO / "showcase" / "config" / "labs.json"
DEPLOY_DIR = Path(__file__).resolve().parent
OUT_DIR = DEPLOY_DIR / "generated"
DATA_DIR = DEPLOY_DIR / "data"
API_IMAGE = "genai-labs-api:latest"
LAB_ID = re.compile(r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?$")
PERSIST_FILE = re.compile(r"^[A-Za-z0-9_.-]+$")


class ConfigError(Exception):
    pass


def load_labs() -> list[dict]:
    config = json.loads(LABS_FILE.read_text())
    labs = [lab for lab in config.get("labs", []) if lab.get("enabled", True)]
    seen: set[str] = set()
    for lab in labs:
        lab_id = lab.get("id", "")
        if not LAB_ID.match(lab_id):
            raise ConfigError(f"lab id {lab_id!r} must be lowercase letters, digits and dashes")
        if lab_id in seen:
            raise ConfigError(f"duplicate lab id {lab_id!r}")
        seen.add(lab_id)
        if not isinstance(lab.get("backendPort"), int):
            raise ConfigError(f"{lab_id}: backendPort must be a number")
        if not (backend_dir(lab) / "main.py").is_file():
            raise ConfigError(f"{lab_id}: no main.py in {backend_dir(lab).relative_to(REPO)}")
        if not (REPO / lab["dir"] / "frontend" / "package.json").is_file():
            raise ConfigError(f"{lab_id}: no frontend/package.json in {lab['dir']}")
        for name in lab.get("persist", []):
            if not isinstance(name, str) or not PERSIST_FILE.match(name) or name.startswith("."):
                raise ConfigError(f"{lab_id}: persist entry {name!r} must be a plain file name")
    return labs


def backend_dir(lab: dict) -> Path:
    return (REPO / lab["dir"] / lab.get("backendDir", "backend")).resolve()


def upstream(lab: dict) -> str:
    return f"api-{lab['id']}:{lab['backendPort']}"


def ensure_data_files(labs: list[dict]) -> None:
    """Bind-mounting a missing host file would create a directory, so create the files first.
    An empty file is a valid empty SQLite database; each lab's init_db() creates its tables."""
    for lab in labs:
        for name in lab.get("persist", []):
            path = DATA_DIR / lab["id"] / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.touch(exist_ok=True)


def render_compose(labs: list[dict]) -> str:
    lines = [
        "# GENERATED by showcase/deploy/render.py from showcase/config/labs.json. Do not edit.",
        "name: genai-labs",
        "services:",
        "  web:",
        "    build:",
        "      context: ../../..",
        "      dockerfile: showcase/deploy/web.Dockerfile",
        "    restart: unless-stopped",
        '    ports: ["80:80", "443:443", "443:443/udp"]',
        "    environment:",
        "      DOMAIN: ${DOMAIN:?set DOMAIN in .env}",
        "      ACME_EMAIL: ${ACME_EMAIL:?set ACME_EMAIL in .env}",
        "      SHOWCASE_ACCESS_KEY: ${SHOWCASE_ACCESS_KEY:?set SHOWCASE_ACCESS_KEY in .env}",
        "    volumes:",
        "      - ./Caddyfile:/etc/caddy/Caddyfile:ro",
        "      # Mounted live: edits to labs.json show up in the open UI without a redeploy.",
        "      - ../../config:/srv/config:ro",
        "      - caddy_data:/data",
        "      - caddy_config:/config",
        "    depends_on: [" + ", ".join(f"api-{lab['id']}" for lab in labs) + "]",
    ]
    for lab in labs:
        workdir = "/app/" + backend_dir(lab).relative_to(REPO).as_posix()
        lines += [
            f"  api-{lab['id']}:",
            f"    image: {API_IMAGE}",
            "    restart: unless-stopped",
            f"    working_dir: {workdir}",
            f"    command: uvicorn main:app --host 0.0.0.0 --port {lab['backendPort']}",
            "    env_file: ../../../.env",
        ]
        if lab.get("persist"):
            lines.append("    volumes:")
            lines += [f"      - ../data/{lab['id']}/{name}:{workdir}/{name}" for name in lab["persist"]]
    lines += ["volumes:", "  caddy_data:", "  caddy_config:"]
    return "\n".join(lines) + "\n"


def render_caddyfile(labs: list[dict]) -> str:
    shell_api_routes = "".join(
        f"\t\thandle_path /api/{lab['id']}/* {{\n\t\t\treverse_proxy {upstream(lab)}\n\t\t}}\n" for lab in labs
    )
    lab_sites = "".join(
        f"""
{lab['id']}.{{$DOMAIN}} {{
\tencode gzip
\troute {{
\t\timport access_gate
\t\thandle_path /api/* {{
\t\t\treverse_proxy {upstream(lab)}
\t\t}}
\t\thandle {{
\t\t\troot * /srv/labs/{lab['id']}
\t\t\ttry_files {{path}} {{path}}/index.html /index.html
\t\t\tfile_server
\t\t}}
\t}}
}}
"""
        for lab in labs
    )
    return f"""# GENERATED by showcase/deploy/render.py from showcase/config/labs.json. Do not edit.
{{
\temail {{$ACME_EMAIL}}
}}

# Every request needs the access cookie, so strangers can't spend the OpenAI quota.
# Visiting https://DOMAIN/unlock?key=<SHOWCASE_ACCESS_KEY> once sets it for DOMAIN and all lab subdomains.
(access_gate) {{
\t@unlock {{
\t\tpath /unlock
\t\tquery key={{$SHOWCASE_ACCESS_KEY}}
\t}}
\theader @unlock Set-Cookie "showcase_access={{$SHOWCASE_ACCESS_KEY}}; Domain={{$DOMAIN}}; Path=/; Max-Age=2592000; Secure; HttpOnly; SameSite=Lax"
\tredir @unlock / 302
\t@locked not header Cookie *showcase_access={{$SHOWCASE_ACCESS_KEY}}*
\trespond @locked "Access key required: open https://{{$DOMAIN}}/unlock?key=YOUR_KEY" 401
}}

# Showcase shell
{{$DOMAIN}} {{
\tencode gzip
\troute {{
\t\timport access_gate
\t\thandle /labs.json {{
\t\t\troot * /srv/config
\t\t\theader Cache-Control no-store
\t\t\tfile_server
\t\t}}
{shell_api_routes}\t\thandle {{
\t\t\troot * /srv/shell
\t\t\ttry_files {{path}} /index.html
\t\t\tfile_server
\t\t}}
\t}}
}}

# One site per lab: its static UI, with its FastAPI backend under /api (same origin, no CORS).
{lab_sites}"""


def render_requirements(labs: list[dict]) -> str:
    """Union of every enabled lab's requirements, so one image runs all backends."""
    packages: dict[str, str] = {}
    for lab in labs:
        for line in (backend_dir(lab) / "requirements.txt").read_text().splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                packages.setdefault(re.split(r"[\[<>=!~ ]", line, 1)[0].lower(), line)
    header = "# GENERATED by showcase/deploy/render.py: union of all enabled labs' requirements.\n"
    return header + "\n".join(sorted(packages.values(), key=str.lower)) + "\n"


def main() -> int:
    try:
        labs = load_labs()
    except (ConfigError, json.JSONDecodeError, KeyError) as err:
        print(f"labs.json is invalid: {err}", file=sys.stderr)
        return 1
    if not labs:
        print("labs.json has no enabled labs", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(exist_ok=True)
    ensure_data_files(labs)
    (OUT_DIR / "docker-compose.yml").write_text(render_compose(labs))
    (OUT_DIR / "Caddyfile").write_text(render_caddyfile(labs))
    (OUT_DIR / "requirements.txt").write_text(render_requirements(labs))
    print(f"Rendered {len(labs)} labs into {OUT_DIR.relative_to(REPO)}/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
