apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genai-ingress
  namespace: genai-lab
spec:
  rules:
    - host: genai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: genai-frontend
                port:
                  number: 3020
